In [ ]:
import pandas as pd
from sodapy import Socrata
from datetime import datetime, timedelta

In [ ]:
client = Socrata("www.dallasopendata.com", None)

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

In [42]:
yesterday = datetime.now() - timedelta(days=1)
date = yesterday.date()
string = "ararrestdate = '" + str(date) + "'"
results = client.get("sdr7-6v3j", where=string)

In [43]:
results_df = pd.DataFrame.from_records(results)
results_df.head(5)

,incidentnum,arrestyr,arrestnumber,ararrestdate,ararresttime,arbkdate,arladdress,arlzip,arlcity,arstate,...,upzdate,arlsector,birthplace,hra,hbeat,drugtype,transport2,occupation,employer,arlapt
0,045268-2025,2025,25-008423,2025-04-01T00:00:00.000,00:58,2025-04-01T03:21:12.000,2626 COMMERCE ST,75226,DALLAS,TX,...,2025-04-01 12:11:28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,045300-2025,2025,25-008430,2025-04-01T00:00:00.000,03:22,2025-04-01T05:30:02.000,400 SANTA FE AVE,75203,DALLAS,TX,...,2025-04-01 05:40:14,710,HONDURAS,6050,711,Powder Cocaine,NaN,NaN,NaN,NaN
2,045404-2025,2025,25-008444,2025-04-01T00:00:00.000,10:00,2025-04-01T13:55:09.000,10100 HARRY HINES BLVD,75220,DALLAS,TX,...,2025-04-01 14:10:22,NaN,"SHREVPORT, LA",8813,123,NaN,11541,NaN,NaN,NaN
3,045650-2025,2025,25-008484,2025-04-01T00:00:00.000,19:33,2025-04-01T21:32:26.000,727 ANN ARBOR AVE,75216,DALLAS,TX,...,2025-04-01 21:38:03,NaN,DALLAS,2088,135,Crack Cocaine,11547,NaN,NaN,NaN
4,045316-2025,2025,25-008433,2025-04-01T00:00:00.000,03:10,2025-04-01T07:08:07.000,5700 N JIM MILLER RD,75228,DALLAS,TX,...,2025-04-01 07:21:12,230,NaN,NaN,NaN,Methamphetamine,NaN,NaN,NaN,NaN

In [48]:
results_df.to_csv("arrest_apr_1st_code.csv", index=False)

In [44]:
results_df.shape

(16, 50)

In [45]:
ress = client.get("sdr7-6v3j", limit = 50)
ress_df = pd.DataFrame.from_records(ress)

In [46]:
ress_df.head()

,incidentnum,arrestyr,arrestnumber,ararrestdate,ararresttime,arbkdate,arladdress,arlzip,arlcity,arstate,...,drugtype,hapt,tatoo,tatoocomment,armedloc,occupation,employer,nickname,arlapt,aliasname
0,045223-2025,2025,25-008419,2025-03-31T00:00:00.000,22:30,2025-04-01T04:16:39.000,2000 EMPIRE CENTRAL,75235,DALLAS,TX,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,050955-2015,2015,15-008928,2015-03-07T00:00:00.000,11:30,2015-03-07T12:39:35.000,2215 S BUCKNER BLVD,75227,DALLAS,TX,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,187719-2021,2021,21-031418,2021-10-15T00:00:00.000,18:21,2021-10-15T20:15:42.000,4435 CINNABAR DR,75227,DALLAS,TX,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,042800-2025,2025,25-007893,2025-03-27T00:00:00.000,13:10,2025-03-27T14:14:33.000,254 S RIVERFRONT BLVD,75207,DALLAS,TX,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,055469-2024,2024,24-008985,2024-04-08T00:00:00.000,21:32,2024-04-09T02:34:56.000,3502 S LANCASTER RD,75216,DALLAS,TX,...,Methamphetamine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
ress_df.shape

(50, 55)

In [49]:
yesterday = datetime.now() - timedelta(days=1)
date = yesterday.date()
query = "SELECT * WHERE ArArrestDate = '" + str(date) + "'"

results = client.get("sdr7-6v3j", query=query)
results_df = pd.DataFrame.from_records(results)
results_df.head(5)

,incidentnum,arrestyr,arrestnumber,ararrestdate,ararresttime,arbkdate,arladdress,arlzip,arlcity,arstate,...,upzdate,arlsector,birthplace,hra,hbeat,drugtype,transport2,occupation,employer,arlapt
0,045268-2025,2025,25-008423,2025-04-01T00:00:00.000,00:58,2025-04-01T03:21:12.000,2626 COMMERCE ST,75226,DALLAS,TX,...,2025-04-01 12:11:28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,045300-2025,2025,25-008430,2025-04-01T00:00:00.000,03:22,2025-04-01T05:30:02.000,400 SANTA FE AVE,75203,DALLAS,TX,...,2025-04-01 05:40:14,710,HONDURAS,6050,711,Powder Cocaine,NaN,NaN,NaN,NaN
2,045404-2025,2025,25-008444,2025-04-01T00:00:00.000,10:00,2025-04-01T13:55:09.000,10100 HARRY HINES BLVD,75220,DALLAS,TX,...,2025-04-01 14:10:22,NaN,"SHREVPORT, LA",8813,123,NaN,11541,NaN,NaN,NaN
3,045650-2025,2025,25-008484,2025-04-01T00:00:00.000,19:33,2025-04-01T21:32:26.000,727 ANN ARBOR AVE,75216,DALLAS,TX,...,2025-04-01 21:38:03,NaN,DALLAS,2088,135,Crack Cocaine,11547,NaN,NaN,NaN
4,045316-2025,2025,25-008433,2025-04-01T00:00:00.000,03:10,2025-04-01T07:08:07.000,5700 N JIM MILLER RD,75228,DALLAS,TX,...,2025-04-01 07:21:12,230,NaN,NaN,NaN,Methamphetamine,NaN,NaN,NaN,NaN

In [ ]:

# Unauthenticated client only works with public data sets. Note 'None'
# in place of application token, and no username or password:
client = Socrata("www.dallasopendata.com", None)

# Example authenticated client (needed for non-public datasets):
# client = Socrata(www.dallasopendata.com,
#                  MyAppToken,
#                  username="user@example.com",
#                  password="AFakePassword")

# First 2000 results, returned as JSON from API / converted to Python list of
# dictionaries by sodapy.
results = client.get("sdr7-6v3j", limit=2000)

# Convert to pandas DataFrame
results_df = pd.DataFrame.from_records(results)